import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { useState } from "react";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

export default function DriverDocketPreview({ docket }) {
  const previewRef = useRef();
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const canvas = await html2canvas(previewRef.current, { scale: 2, useCORS: true, backgroundColor: "#ffffff" });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pdfW = pdf.internal.pageSize.getWidth();
      const pdfH = (canvas.height * pdfW) / canvas.width;
      pdf.addImage(imgData, "PNG", 0, 0, pdfW, pdfH);
      pdf.save(`${docket.ticket_no || "driver-docket"}.pdf`);
    } finally {
      setDownloading(false);
    }
  };

  const row = (label, value) => value ? (
    <div className="flex justify-between items-start py-2 border-b border-[#EAEEF5] last:border-b-0">
      <span className="text-[10px] font-bold uppercase tracking-widest text-[#7A8898] w-28 shrink-0">{label}</span>
      <span className="text-xs font-semibold text-right" style={{ color: 'var(--mx-text)' }}>{value}</span>
    </div>
  ) : null;

  return (
    <div className="w-full">
      {/* Downloadable Preview */}
      <div ref={previewRef} className="bg-white rounded-[18px] border border-[#EAEEF5] p-6 text-left">
        {/* Header */}
        <div className="flex items-start justify-between mb-5 pb-4 border-b-2 border-[#1E4D99]">
          <div>
            <img
              src="https://media.base44.com/images/public/69f7b7e128899b8db1200527/c72ebbf3f_MetalXLogo.png"
              alt="Metal X" className="h-8 object-contain mb-1"
            />
            <p className="text-[9px] font-bold tracking-[2px] text-[#5BA3F5]">METAL X RENEWABLES</p>
            <p className="text-[8px] text-[#7A8898]">PO BOX Z5150, ST GEORGES TERRACE 6000</p>
          </div>
          <div className="text-right">
            <p className="text-[10px] font-bold tracking-[2px] text-[#7A8898] uppercase">Driver Docket</p>
            <p className="text-lg font-black" style={{ color: 'var(--mx-text)' }}>{docket.ticket_no}</p>
            <p className="text-[10px] text-[#7A8898]">{docket.order_date}</p>
          </div>
        </div>

        {/* Weight Summary */}
        <div className="grid grid-cols-3 gap-2 mb-5">
          {[
            { label: "GROSS", value: docket.gross_tonnes, unit: "T" },
            { label: "TARE", value: docket.tare_tonnes, unit: "T" },
            { label: "NET", value: docket.net_tonnes, unit: "T" },
          ].map(({ label, value, unit }) => (
            <div key={label} className="bg-[#EFF4FF] rounded-[12px] p-3 text-center">
              <p className="text-[9px] font-bold tracking-widest text-[#5BA3F5]">{label}</p>
              <p className="text-xl font-black text-[#1E4D99]">{value || "—"}</p>
              <p className="text-[9px] text-[#5BA3F5]">{unit}</p>
            </div>
          ))}
        </div>

        {/* Details */}
        <div className="space-y-0">
          {row("REGO", docket.rego)}
          {row("DRIVER", docket.driver_name)}
          {row("CUSTOMER", docket.customer_name)}
          {row("GOODS", docket.goods_weighed)}
          {row("GRADE", docket.material_grade)}
          {row("FROM", docket.from_location)}
          {row("TO", docket.to_location)}
          {row("SCHEDULE", docket.schedule_id)}
          {row("NOTES", docket.comments)}
          {docket.contamination_notes && (
            <div className="mt-3 p-3 bg-amber-50 border border-amber-200 rounded-[8px]">
              <p className="text-[9px] font-bold uppercase tracking-widest text-amber-700 mb-0.5">CONTAMINATION</p>
              <p className="text-xs text-amber-800">{docket.contamination_notes}</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="mt-5 pt-3 border-t border-[#EAEEF5] flex justify-between items-center">
          <p className="text-[8px] text-[#AAB0C4]">Generated by Metal X Document Studio</p>
          <p className="text-[8px] font-bold text-[#AAB0C4]">STATUS: {docket.status}</p>
        </div>
      </div>

      {/* Download Button */}
      <Button
        onClick={handleDownload}
        disabled={downloading}
        className="w-full mt-4 h-12 text-sm font-bold rounded-[12px] text-white"
        style={{ background: 'var(--mx-hero-gradient)' }}
      >
        {downloading
          ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" />GENERATING PDF…</>
          : <><Download className="w-4 h-4 mr-2" />DOWNLOAD DOCKET PDF</>}
      </Button>
    </div>
  );
}